# -*- coding: utf-8 -*-
"""kpiahorro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1db0uBGOP45KhDC59Gpk9yJFaXWTiNM67
"""

def ahorro_interes_compuesto_diario(montos_diarios, tasa_anual=0.10, meses=12):
    dias_totales = meses * 30  # Aproximando cada mes a 30 días
    tasa_diaria = (1 + tasa_anual) ** (1/365) - 1
    historial = []
    ahorro_acumulado = 0

    for i in range(dias_totales):
        monto = montos_diarios[i] if i < len(montos_diarios) else 0
        ahorro_acumulado = (ahorro_acumulado + monto) * ( 1 + tasa_diaria)
        historial.append(round(ahorro_acumulado, 2))

    return historial
