# -*- coding: utf-8 -*-
"""porcentajenegociosyfrecuenciadecompras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzuWqPu0MWD6bcGEJtbZU0pno1A-qFl_
"""

import plotly.express as px

def graficar_top5_comercios(usuario_id, df):
    # Filtrar datos del usuario
    df_user = df[df['id'] == usuario_id]

    if df_user.empty:
        print(f"No se encontraron datos para {usuario_id}.")
        return

    # Calcular gasto total
    gasto_total = df_user['monto'].sum()

    # Agrupar y calcular porcentaje
    gasto_por_comercio = (
        df_user.groupby('comercio')['monto']
        .sum()
        #.apply(lambda x: round((x / gasto_total) * 100, 2))
        .reset_index()
        .rename(columns={'comercio':'Comercio','monto': 'Gasto Total'})
        .sort_values(by='Gasto Total', ascending=False)
    )

    # Top 5
    top5 = gasto_por_comercio.head(5)

    return top5

#graficar_top5_comercios('Usuario 1', df_merged)

import plotly.express as px

def graficar_frecuencia(usuario_id, df, frecuencia='M'):
    frecuencia_usuario = kpi_frecuencia_compras(usuario_id, df, frecuencia)

    if frecuencia_usuario.empty:
        return

    fig = px.line(
        frecuencia_usuario,
        x='fecha',
        y='transacciones',
        title=f'Frecuencia de Compras ({frecuencia}) - {usuario_id}',
        markers=True
    )
    fig.update_layout(xaxis_title='Fecha', yaxis_title='Cantidad de Transacciones')
    fig.show()

#graficar_frecuencia('Usuario 1', df_merged, frecuencia='M')

#graficar_frecuencia('Usuario 1', df_merged, frecuencia='W')  # semanal